spring:
  banner:
    location: classpath:banner.txt
  rabbitmq:
    addresses: MQ_ADDRESSES

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    com.github.bucket4j: DEBUG
    com.ced: DEBUG

twilio:
  account-sid: TWILIO_ACCOUNT_SID
  auth-token: TWILIO_AUTH_TOKEN
  phone-number: TWILIO_PHONE_NUMBER

sendgrid:
  api-key: SENDGRID_API_KEY
  sender-email: SENDGRID_SENDER_EMAIL

security:
  token: SECURITY_TOKEN_PASSWORD
  expiration: SECURITY_TOKEN_EXPIRATION

amqp:
  exchange-name: EXCHANGE_NAME
  queue-name: QUEUE_NAME
  routing-key: ROUTING_KEY
