spring:
  banner:
    location: classpath:banner.txt

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    com.github.bucket4j: DEBUG
    com.ced: DEBUG

cors:
  allowed-origins:
    - https://characters.discloud.app
    - https://whisp.discloud.app
    - http://localhost:4200
    - https://cavernas-e-dragoes.web.app
    - https://cavernasedragoes.com.br
    - https://www.cavernasedragoes.com.br

twilio:
  account-sid: TWILIO_ACCOUNT_SID_PLACEHOLDER
  auth-token: TWILIO_AUTH_TOKEN_PLACEHOLDER
  phone-number: TWILIO_PHONE_NUMBER_PLACEHOLDER

sendgrid:
  api-key: SENDGRID_API_KEY_PLACEHOLDER
  sender-email: SENDGRID_SENDER_EMAIL_PLACEHOLDER

security:
  token: SECURITY_TOKEN_PASSWORD_PLACEHOLDER
  expiration: SECURITY_TOKEN_EXPIRATION_PLACEHOLDER
